# Generated by Django 4.0.4 on 2023-05-29 12:21

from django.db import migrations
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goods_options_alter_goodsimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=simditor.fields.RichTextField(),
        ),
    ]
