# Generated by Django 4.2.1 on 2023-05-05 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0002_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=16)),
                ('launchDate', models.CharField(max_length=16)),
                ('platform', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhoneReview.brand', verbose_name='')),
            ],
        ),
    ]
