# Generated by Django 4.2.1 on 2023-05-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0003_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='platform',
        ),
    ]
