# Generated by Django 4.2.1 on 2023-05-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0004_remove_model_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='platform',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='model',
            name='launchDate',
            field=models.IntegerField(),
        ),
    ]
