# Generated by Django 4.2.1 on 2023-05-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0005_model_platform_alter_model_launchdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='platform',
            field=models.SmallIntegerField(choices=[(1, 'Android'), (2, 'iOS'), (3, 'windowsPhone'), (4, 'Harmony')], verbose_name=''),
        ),
    ]
