# Generated by Django 4.2.1 on 2023-05-05 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0006_alter_model_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('dataPublish', models.IntegerField()),
                ('link', models.CharField(max_length=16)),
                ('relatedModle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhoneReview.model', verbose_name='')),
            ],
        ),
    ]
