# Generated by Django 4.2.1 on 2023-05-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dataPublish',
            field=models.CharField(max_length=16),
        ),
    ]
