# Generated by Django 4.2.1 on 2023-05-05 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0008_alter_review_datapublish'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='relatedBrand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PhoneReview.brand', verbose_name='Related Brand'),
        ),
        migrations.AlterField(
            model_name='review',
            name='dataPublish',
            field=models.CharField(max_length=16, verbose_name='Data Publish'),
        ),
        migrations.AlterField(
            model_name='review',
            name='link',
            field=models.CharField(max_length=16, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='review',
            name='relatedModle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhoneReview.model', verbose_name='Related Modle'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=16, verbose_name='Title'),
        ),
    ]
