# Generated by Django 4.2.1 on 2023-05-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0010_alter_review_relatedbrand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='relatedBrand',
        ),
        migrations.AddField(
            model_name='review',
            name='relatedbrand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PhoneReview.brand', verbose_name=''),
        ),
    ]
