# Generated by Django 4.0.4 on 2023-05-24 07:07

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Goods SPU', 'verbose_name_plural': 'Goods SPU'},
        ),
        migrations.AlterModelOptions(
            name='goodsimage',
            options={'verbose_name': 'Goods Images', 'verbose_name_plural': 'Goods Images'},
        ),
        migrations.AlterModelOptions(
            name='goodssku',
            options={'verbose_name': 'Goods SKU', 'verbose_name_plural': 'Goods SKU'},
        ),
        migrations.AlterModelOptions(
            name='goodstype',
            options={'verbose_name': 'Goods Type Table', 'verbose_name_plural': 'Goods Type Table'},
        ),
        migrations.AlterModelOptions(
            name='indexcreatorygoods',
            options={'verbose_name': 'Index Category Goods Table', 'verbose_name_plural': 'Index Category Goods Table'},
        ),
        migrations.AlterModelOptions(
            name='indexgoodsbanner',
            options={'verbose_name': 'Index Banner Table', 'verbose_name_plural': 'Index Banner Table'},
        ),
        migrations.AlterModelOptions(
            name='indexpromotion',
            options={'verbose_name': 'Index Event Table', 'verbose_name_plural': 'Index Event Table'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Goods Details'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='Delete Marker'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Goods SPU Name'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodssku', verbose_name='Goods sku associated id'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='Delete Marker'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='path',
            field=models.ImageField(upload_to='goods', verbose_name='Image path'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='desc',
            field=models.CharField(max_length=256, verbose_name='Goods Desc'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='Goods SPU'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='image',
            field=models.ImageField(upload_to='goods', verbose_name='Goods Image'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='Delete Marker'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Goods Name'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Goods Price'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='Sales'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Remove from the shelves'), (1, 'On the shelf')], default=1, verbose_name='Goods State'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodstype', verbose_name='Associated Goods types'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='unite',
            field=models.CharField(max_length=20, verbose_name='Unite'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='image',
            field=models.ImageField(upload_to='type', verbose_name='Goods Type image'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='Delete Marker'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='logo',
            field=models.CharField(max_length=20, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Type Name'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='indexcreatorygoods',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='indexcreatorygoods',
            name='display_mode',
            field=models.SmallIntegerField(choices=[(0, 'Title'), (1, 'Image')], default=1, verbose_name='Display Mode'),
        ),
        migrations.AlterField(
            model_name='indexcreatorygoods',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodssku', verbose_name='Goods id'),
        ),
        migrations.AlterField(
            model_name='indexcreatorygoods',
            name='index',
            field=models.SmallIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='indexcreatorygoods',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='Delete Marker'),
        ),
        migrations.AlterField(
            model_name='indexcreatorygoods',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodstype', verbose_name='Goods Type id'),
        ),
        migrations.AlterField(
            model_name='indexcreatorygoods',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodssku', verbose_name='Goods id'),
        ),
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='image',
            field=models.ImageField(upload_to='index', verbose_name='Rotation picture'),
        ),
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='index',
            field=models.SmallIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='Delete Marker'),
        ),
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='indexpromotion',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='indexpromotion',
            name='image',
            field=models.ImageField(upload_to='index', verbose_name='Event image'),
        ),
        migrations.AlterField(
            model_name='indexpromotion',
            name='index',
            field=models.SmallIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='indexpromotion',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='Delete Marker'),
        ),
        migrations.AlterField(
            model_name='indexpromotion',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='indexpromotion',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='indexpromotion',
            name='url',
            field=models.CharField(max_length=256, verbose_name='Event Url'),
        ),
    ]
