# Generated by Django 4.0.4 on 2023-05-24 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goods_options_alter_goodsimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_alter_address_create_time_alter_address_is_del_and_more'),
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'verbose_name': 'Order Goods Table', 'verbose_name_plural': 'Order Goods Table'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': 'Order Info Table', 'verbose_name_plural': 'Order Info Table'},
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='comment',
            field=models.CharField(max_length=256, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Number of Goods'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='goods_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodssku', verbose_name='Goods id'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='Delete Marker'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='order_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderinfo', verbose_name='Order id'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price of goods'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.address', verbose_name='Addr id'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='Delete Marker'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Order id'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_methods',
            field=models.SmallIntegerField(choices=[(1, 'Cash on delivery'), (2, 'WeChat pay'), (3, 'Alipay'), (4, 'UnionPay')], default=3, verbose_name='Payment Methods'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'To be paid'), (2, 'To be shipped'), (3, 'To be received'), (4, 'To be evaluated'), (5, 'Completed')], default=1, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='total_count',
            field=models.IntegerField(default=1, verbose_name='Total number of Goods'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total price of goods'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_no',
            field=models.CharField(default='', max_length=128, verbose_name='Trade no.'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='transit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Order shipping cost'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User id'),
        ),
    ]
